---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=600']
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: flakeheaven
        name: flakeheaven
        description: "`FlakeHeaven` it's a Flake8 wrapper to make it cools."
        entry: poetry run flakeheaven
        args: [lint]
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.22.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
