---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.0
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible-community/ansible-lint.git
    sha: v5.0.6
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
