---
# RPI setup.
rpi_locale: en_US.UTF-8
rpi_layout: us
rpi_dist_upgrade: no
rpi_tz: 'Europe/Amsterdam'
rpi_wifi_country: NL
rpi_swap_config:
  CONF_SWAPSIZE: 100
  # CONF_SWAPFILE: /var/swap
  # CONF_SWAPFACTOR: 2
  # CONF_MAXSWAP: 2048
rpi_latlong: 51.9812,5.6584

# Security configuration.
security_sudoers_passworded: ['pi']
firewall_allowed_tcp_ports:
  - 22
  - 53
  - 80
  - 443
  - 548
firewall_allowed_udp_ports:
  - 53
  - 67
  - 5353
  - 5354
firewall_flush_rules_and_chains: no

# LCD configuration.
enable_lcd: true
lcd_type: MPI3501
lcd_rotate: 270
