---
- hosts: lcd
  become: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

    - import_tasks: tasks/init.yml

  roles:
    - role: geerlingguy.security
      tags: ['security', 'ssh']

    - role: geerlingguy.firewall
      tags: ['security', 'firewall']

    - role: geerlingguy.git
      tags: ['git']

    - role: geerlingguy.pip
      tags: ['pip']

    - role: geerlingguy.docker_arm
      tags: ['docker']

    - role: fedejaure.rpi_lcd
      tags: ['lcd']

  tasks: []
