---
- hosts: otacon
  become: yes

  vars_files:
    - default.config.yml

  vars:
    - rpi_hostname: otacon
    - rpi_docker_compose_project: "{{ rpi_hostname }}"
    - rpi_docker_compose_project_config:
        templates:
          - src: "{{ rpi_docker_compose_project }}/docker-compose.yml"
            project_dest: "docker-compose.yml"

        virtual_hosts:
          whoami: "whoami.{{ rpi_hostname }}.local"

    - rpi_virtual_hosts_aliases: "{{ rpi_docker_compose_project_config.virtual_hosts.values() | list }}"

  pre_tasks:
    - name: Include config override file, if it exists
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

    - import_tasks: tasks/init.yml
      tags: ['init']

  roles:
    - role: geerlingguy.security
      tags: ['security', 'ssh']

    - role: geerlingguy.firewall
      tags: ['security', 'firewall']

    - role: geerlingguy.git
      tags: ['git']

    - role: geerlingguy.pip
      tags: ['pip']

    - role: geerlingguy.docker_arm
      tags: ['docker']

    - role: fedejaure.rpi_lcd
      tags: ['lcd']

  handlers:

    - import_tasks: handlers/main.yml

  tasks:

    - import_tasks: tasks/docker_compose.yml
      tags: ['docker-compose']
