---
roles:
  - name: geerlingguy.security
    version: 2.2.0
  - name: geerlingguy.firewall
    version: 2.5.1
  - name: geerlingguy.git
    version: 3.0.1
  - name: geerlingguy.pip
    version: 2.2.0
  - name: geerlingguy.supervisor
    version: 3.1.1
  - name: geerlingguy.docker
    version: 6.1.0
  - name: fedejaure.rpi_lcd
    version: 0.2.0

collections:
  - name: community.docker
    version: 3.4.3
  - name: community.general
    version: 6.5.0
