---
roles:
  - geerlingguy.security
  - geerlingguy.firewall
  - geerlingguy.git
  - geerlingguy.pip
  - geerlingguy.supervisor
  - geerlingguy.docker_arm
  - fedejaure.rpi_lcd

collections:
  - community.docker
  - community.general
