---
- name: Make sure avahi aliases requirements are present
  apt:
    name: ["python-avahi", "python-daemon"]
    state: present

- name: Install avahi aliases
  pip:
    name: git+git://github.com/airtonix/avahi-aliases.git
    virtualenv_python: python2.7

- name: Copy alias service configuration file
  copy:
    src: etc/systemd/system/avahi-alias.service
    dest: /etc/systemd/system/avahi-alias.service
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x
  notify: Restart avahi alias service

- name: Configure virtual hosts aliases
  lineinfile:
    path: /etc/avahi/aliases.d/default
    state: present
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x
    line: "{{ item }}"
    create: yes
  with_items: "{{ rpi_virtual_hosts_aliases }}"
  notify: Restart avahi alias service
