---
- name: Check unpartitioned space
  shell: |
    set -o pipefail
    /sbin/parted /dev/mmcblk0 unit gb print free | grep 'Free Space' | tail -n1 | awk '{print $3}'
  register: unpartitioned
  changed_when: false
  failed_when: unpartitioned.stderr
  args:
    executable: /usr/bin/bash

- name: Expand filesystem to fill disk
  command: raspi-config --expand-rootfs
  when: unpartitioned.stdout != "0.00GB"

- name: Reboot after file system change
  reboot:
    reboot_timeout: 300
  when: unpartitioned.stdout != "0.00GB"

- name: Update apt cache if needed
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Upgrade the OS
  apt:
    upgrade: dist
  when: rpi_dist_upgrade is defined and rpi_dist_upgrade

- name: Check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if needed
  reboot:
    reboot_timeout: 300
  when: reboot_required.stat.exists

- name: Ensure dev packages are instaled
  apt:
    name:
      - build-essential
      - libssl-dev
      - libffi-dev
    state: present

- name: Get current locale and layout configuration
  command: localectl status
  register: locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration
  set_fact:
    current_locale: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Parse 'Layout' from X11 Layout
  set_fact:
    current_layout: "{{ locale_status.stdout | regex_search('X11 Layout: ([^\n]+)', '\\1') | first }}"

- name: Change locale
  command: "raspi-config nonint do_change_locale {{ rpi_locale }}"
  when: current_locale != rpi_locale

- name: Change keyboard layout
  command: "raspi-config nonint do_configure_keyboard {{ rpi_layout }}"
  when: current_layout != rpi_layout

- name: Set the hostname
  become: yes
  command: hostnamectl set-hostname "{{ rpi_hostname }}"
  changed_when: false

- name: Update /etc/hosts with new hostname
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1  raspberrypi$"
    line: "127.0.1.1  {{ rpi_hostname }}"
    state: present
