version: "3.8"

services:

  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: containous/whoami
    restart: always
    environment:
      - VIRTUAL_HOST={{ rpi_docker_compose_project_config.virtual_hosts.whoami }}
      - WHOAMI_NAME={{ rpi_hostname }}
