---
- hosts:
    - otacon
    - ocelot
  tasks:
    - name: create /etc/docker.
      ansible.builtin.file:
        state: directory
        path: /etc/docker

    - name: Set storage-driver to vfs via daemon.json.
      ansible.builtin.copy:
        content: |
          {
            "debug": false,
            "default-cgroupns-mode": "host",
            "storage-driver": "vfs"
          }
        dest: /etc/docker/daemon.json
        mode: "600"
