---
- hosts: all
  tasks:
    - name: create /etc/docker.
      file:
        state: directory
        path: /etc/docker

    - name: Set storage-driver to vfs via daemon.json.
      copy:
        content: |
          {
            "storage-driver": "vfs"
          }
        dest: /etc/docker/daemon.json
        mode: '600'
