---
- name: Ensure mdns-beacon is installed.
  ansible.builtin.pip:
    name: mdns-beacon
    state: present
    version: "{{ mdns_beacon_version | default(omit) }}"
    executable: "{{ pip_executable }}"
