---
- name: Reboot raspi
  ansible.builtin.reboot:
    reboot_timeout: 300
  listen: reboot raspi is required

- name: Prune services
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
  listen: prune services is required
