---
- name: Reboot raspi
  ansible.builtin.reboot:
    reboot_timeout: 300
  listen: reboot raspi is required

- name: Prune services
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true
  listen: prune services is required

- name: Setup swap file
  ansible.builtin.command: dphys-swapfile setup
  register: swap_setup
  changed_when: "'generating swapfile' in swap_setup.stdout"
  listen: setup swap file is required
  notify: activate swap is required

- name: Activate swap
  ansible.builtin.command: dphys-swapfile swapon
  listen: activate swap is required
