---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: otacon
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    ansible_groups:
      - docker-hosts
provisioner:
  name: ansible
  inventory:
    group_vars:
      docker-hosts:
        # This should allow docker-in-docker to work
        docker_storage_driver: vfs

    host_vars:
      otacon:
        ansible_user: root
verifier:
  name: ansible
