name: tests
on: [push, pull_request]
jobs:

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install system deps
        run: pip install pipenv
      - name: Install ansible requirements
        run: pipenv sync --dev
      - name: Linting
        run: pipenv run pre-commit run --all-files
