name: tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  tests:
    needs: linting
    name: molecule-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10
          - debian11
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9

      - name: Install system deps
        shell: bash
        run: pip install pipenv

      - name: Install dev requirements
        shell: bash
        run: pipenv sync --dev

      - name: Install playbooks requirements
        shell: bash
        run: pipenv run inv galaxy-install

      - name: Run Molecule tests
        run: pipenv run inv test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
