name: tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        shell: bash
        run: |
          pip install poetry
          pip install poetry-plugin-export
          poetry config virtualenvs.in-project true
          poetry install --no-root --only dev --sync

      - name: Install playbooks requirements
        shell: bash
        run: poetry run inv galaxy-install

      - name: Linting
        shell: bash
        run: poetry run inv hooks

  tests:
    needs: linting
    name: molecule-${{ matrix.target }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10
          - debian11
        target:
          - otacon
          - ocelot
      fail-fast: false

    steps:
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          df -h

      - uses: actions/checkout@v4.1.2

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        shell: bash
        run: |
          pip install poetry
          pip install poetry-plugin-export
          poetry config virtualenvs.in-project true
          poetry install --no-root

      - name: Install playbooks requirements
        shell: bash
        run: poetry run inv galaxy-install

      - name: Run security checks
        shell: bash
        run: poetry run inv security

      - name: Run Molecule tests
        run: poetry run inv tests --target ${{ matrix.target }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
